name: ping

on:
  schedule:
    - cron: "0 * * JAN *"

jobs:
  ping:
    runs-on: ubuntu-18.04
    steps:
      - uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://phonebook-fs-2021-saari.herokuapp.com/health
          retry-all: no
